name: Run PostgreSQL Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_DB: test_db
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Wait for PostgreSQL
      run: sleep 10

    - name: 🔍 List files for debugging
      run: |
        echo "Mostrando archivos actuales del repositorio:"
        ls -la

    - name: Set up database schema and data
      run: |
        echo "Ejecutando script: 01_Createtables.sql"
        PGPASSWORD=postgres psql -h localhost -U postgres -d test_db -f 01_Createtables.sql

    - name: Insert data
      run: |
        echo "Ejecutando script: 02_Insert_data.sql"
        PGPASSWORD=postgres psql -h localhost -U postgres -d test_db -f 02_Insert_data.sql      

    - name: Run delete script
      run: |
        echo "Ejecutando script: 03_Eliminar.sql"
        PGPASSWORD=postgres psql -h localhost -U postgres -d test_db -f 03_Eliminar.sql  

    - name: Run increase price script
      run: |
        echo "Ejecutando script: 04_Aumentar_precios.sql"
        PGPASSWORD=postgres psql -h localhost -U postgres -d test_db -f 04_Aumentar_precios.sql

    - name: Run update product script
      run: |
        echo "Ejecutando script: 05_Actualizar_producto.sql"
        PGPASSWORD=postgres psql -h localhost -U postgres -d test_db -f 05_Actualizar_producto.sql

    - name: Run range script
      run: |
        echo "Ejecutando script: 06_Rango.sql"
        PGPASSWORD=postgres psql -h localhost -U postgres -d test_db -f 06_Rango.sql

    - name: Run tests
      run: |
        echo "Ejecutando pruebas con pytest..."
        pytest
