name: Run PostgreSQL Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_DB: test_db
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.X'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Wait for PostgreSQL
      run: |
        sleep 10

    - name: O1 Create tables
      run: |
        PGPASSWORD=postgres psql -h localhost -U postgres -d test_db -f ${{ github.workspace }}/01_Create_tables.sql

    - name: Insert data
      run: |
        PGPASSWORD=postgres psql -h localhost -U postgres -d test_db -f ${{ github.workspace }}/02_insert_data.sql     

    - name: Funcion Eliminar
      run: |
         PGPASSWORD=postgres psql -h localhost -U postgres -d test_db -f ${{ github.workspace }}/Ejercicio_eliminar.sql 

    - name: Funcion aumentar precios
      run: |
         PGPASSWORD=postgres psql -h localhost -U postgres -d test_db -f ${{ github.workspace }}/Ejercicio_aumentar_precio.sql

    - name: Funcion rango precios
      run: |
         PGPASSWORD=postgres psql -h localhost -U postgres -d test_db -f ${{ github.workspace }}/Ejercicio_rangos_precios.sql
        
    - name: Run tests
      run: |
        pytest
